# Â© Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.appNames.ui }}-secrets
  namespace: {{ .Values.global.namespace }}
data:
  MAPBOX_TOKEN: {{ .Values.global.mapbox.token | b64enc }}
  CESIUM_TOKEN: {{ .Values.global.cesium.token | b64enc }}
  STUDIO_API_KEY: {{ .Values.global.gfmStudioGateway.api_key | b64enc }}
  OAUTH_CLIENTID: {{ .Values.global.oauth.clientId | b64enc }}
  OAUTH_LOGIN_HINT: {{ .Values.global.oauth.loginHint | b64enc }}
  OAUTH_PROMPT: {{ .Values.global.oauth.prompt | b64enc }}
  OAUTH_RESPONSE_TYPE: {{ .Values.global.oauth.responseType | b64enc }}
  OAUTH_SCOPE: {{ .Values.global.oauth.scope | b64enc }}
  OAUTH_URL: {{ .Values.global.oauth.oauthUrl | b64enc }}
type: Opaque
---
{{- /* tls secret for kubernetes environment */ -}}
{{- if and (.Values.global.oauth.oauthProxyEnabled)  (.Values.global.oauth.createTLSSecret)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appNames.ui }}-authentication-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.oauth.tlsCrtB64 }}
  tls.key: {{ .Values.global.oauth.tlsKeyB64 }}
{{- end }}
