# Â© Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
imagePullSecrets:
  - name: {{ .Values.global.imagePullSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.name }}-secret
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount.name }}-rb
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccount.name }}-role
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount.name }}-role
  namespace: {{ .Values.global.namespace }}
{{- with .Values.rbac.role.rules }}
rules:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
