# Â© Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


{{- if .Values.celery.flower.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.global.appNames.gateway }}-celery
    ingress-router: cash
  annotations:
    haproxy.router.openshift.io/timeout: 2700s
  name: {{ .Values.celery.flower.componentName }}
spec:
  port:
  targetPort: oauth
  to:
    kind: Service
    name: {{ printf "%s-%s" .Release.Name .Values.celery.flower.componentName }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  wildcardPolicy: None
{{- end -}}
