# Â© Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appNames.gateway }}-celery
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.global.appNames.gateway }}-celery-authentication-tls
  labels:
    app: {{ .Values.global.appNames.gateway }}-celery
spec:
  type: {{ .Values.celery.flower.service.type }}
  {{- with .Values.celery.flower.service.port }}
  ports:
    - port: {{ .number }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    app: {{ .Values.global.appNames.gateway }}-celery
    app.kubernetes.io/component: {{ .Values.celery.name }}
