# Â© Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appNames.mlflow }}-secrets
type: Opaque
data:
  BACKEND_URI: {{ (printf "%s/%s" (.Values.global.postgres.backend_uri_base | replace "+pg8000" "") .Values.global.postgres.dbs.mlflow) | b64enc }}
